name: Code Quality
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analyze
        run: ./mvnw verify sonar:sonar
      - uses: sonarsource/sonarqube-quality-gate-action@v1.1.0